spring:
  application:
    name: springmvc

    messages:
      basename: messages
      encoding: UTF-8
      cache-duration: 0







server:
  port: 8080
  error:
    whitelabel:
      enabled: false
